"""Provider-independent domain enumerations."""

from enum import StrEnum


class UserRole(StrEnum):
    USER = "USER"
    ADMIN = "ADMIN"
    OWNER = "OWNER"


class QualityProfile(StrEnum):
    MP3_128 = "MP3_128"
    MP3_320 = "MP3_320"
    AAC_256 = "AAC_256"
    LOSSLESS = "LOSSLESS"


class QualityResolutionStatus(StrEnum):
    RESOLVED = "RESOLVED"
    NO_AVAILABLE_PROVIDER = "NO_AVAILABLE_PROVIDER"
    QUALITY_UNAVAILABLE = "QUALITY_UNAVAILABLE"


class DownloadPlanOperation(StrEnum):
    DIRECT = "DIRECT"
    TRANSCODE = "TRANSCODE"


class DownloadPlanReadiness(StrEnum):
    CONFIRMED = "CONFIRMED"
    REQUIRES_PREFLIGHT = "REQUIRES_PREFLIGHT"


class DownloadPlanReason(StrEnum):
    NATIVE_EXACT_MATCH = "NATIVE_EXACT_MATCH"
    LOSSLESS_TO_REQUESTED_LOSSY = "LOSSLESS_TO_REQUESTED_LOSSY"
    PROVIDER_PREFLIGHT_REQUIRED = "PROVIDER_PREFLIGHT_REQUIRED"


class DownloadAttemptStatus(StrEnum):
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"
    SUCCEEDED = "SUCCEEDED"


class DownloadFailureCode(StrEnum):
    NO_AVAILABLE_PROVIDER = "NO_AVAILABLE_PROVIDER"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    DOWNLOAD_TIMEOUT = "DOWNLOAD_TIMEOUT"
    SOURCE_REQUIREMENT_MISMATCH = "SOURCE_REQUIREMENT_MISMATCH"
    SOURCE_VALIDATION_FAILED = "SOURCE_VALIDATION_FAILED"
    INVALID_PLAN = "INVALID_PLAN"
    TEMP_STORAGE_UNAVAILABLE = "TEMP_STORAGE_UNAVAILABLE"
    MEDIA_PROBE_UNAVAILABLE = "MEDIA_PROBE_UNAVAILABLE"
    MEDIA_PROBE_FAILED = "MEDIA_PROBE_FAILED"
    TRANSCODER_UNAVAILABLE = "TRANSCODER_UNAVAILABLE"
    TRANSCODE_FAILED = "TRANSCODE_FAILED"
    OUTPUT_VALIDATION_FAILED = "OUTPUT_VALIDATION_FAILED"


class QueueJobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SubscriberStatus(StrEnum):
    WAITING = "WAITING"
    READY = "READY"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TelegramMediaKind(StrEnum):
    AUDIO = "AUDIO"
    DOCUMENT = "DOCUMENT"


class TelegramCacheStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INVALID = "INVALID"


class DeliveryPreparationStatus(StrEnum):
    CACHE_HIT = "CACHE_HIT"
    PENDING = "PENDING"


class TelegramDeliveryStatus(StrEnum):
    AWAITING_QUALITY = "AWAITING_QUALITY"
    AWAITING_ACTION = "AWAITING_ACTION"
    AWAITING_TRACK_QUALITY = "AWAITING_TRACK_QUALITY"
    QUEUED = "QUEUED"
    WAITING = "WAITING"
    SENDING = "SENDING"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TelegramDeliveryErrorCode(StrEnum):
    DELIVERY_FAILED = "DELIVERY_FAILED"
    INVALID_CACHED_FILE = "INVALID_CACHED_FILE"
    NO_AVAILABLE_PROVIDER = "NO_AVAILABLE_PROVIDER"
    QUALITY_UNAVAILABLE = "QUALITY_UNAVAILABLE"
    PROVIDER_AUTH_UNAVAILABLE = "PROVIDER_AUTH_UNAVAILABLE"


class AlbumRequestStatus(StrEnum):
    AWAITING_QUALITY = "AWAITING_QUALITY"
    AWAITING_ACTION = "AWAITING_ACTION"
    AWAITING_ALBUM_QUALITY = "AWAITING_ALBUM_QUALITY"
    SELECTING_TRACKS = "SELECTING_TRACKS"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    PARTIALLY_FAILED = "PARTIALLY_FAILED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AlbumItemResolutionStatus(StrEnum):
    PENDING = "PENDING"
    RESOLVING = "RESOLVING"
    ATTACHED = "ATTACHED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class QueueErrorCode(StrEnum):
    QUEUE_FULL = "QUEUE_FULL"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    INVALID_JOB_STATE = "INVALID_JOB_STATE"
    WORKER_LIMIT_EXCEEDED = "WORKER_LIMIT_EXCEEDED"
    DOWNLOAD_PIPELINE_ERROR = "DOWNLOAD_PIPELINE_ERROR"
    DOWNLOAD_PERSISTENCE_ERROR = "DOWNLOAD_PERSISTENCE_ERROR"
    DOWNLOAD_WORKER_ERROR = "DOWNLOAD_WORKER_ERROR"
    UPLOAD_RETRYABLE = "UPLOAD_RETRYABLE"
    UPLOAD_TERMINAL = "UPLOAD_TERMINAL"
    UPLOAD_ARTIFACT_MISSING = "UPLOAD_ARTIFACT_MISSING"
    UPLOAD_ARTIFACT_INVALID = "UPLOAD_ARTIFACT_INVALID"
    UPLOAD_WORKER_ERROR = "UPLOAD_WORKER_ERROR"
    SUBSCRIBER_NOT_FOUND = "SUBSCRIBER_NOT_FOUND"
    INVALID_REQUEST_KEY = "INVALID_REQUEST_KEY"
    TELEGRAM_AUTH_FAILED = "TELEGRAM_AUTH_FAILED"
    TELEGRAM_PERMISSION_DENIED = "TELEGRAM_PERMISSION_DENIED"
    TELEGRAM_BAD_REQUEST = "TELEGRAM_BAD_REQUEST"
    TELEGRAM_RATE_LIMITED = "TELEGRAM_RATE_LIMITED"
    TELEGRAM_TRANSPORT_ERROR = "TELEGRAM_TRANSPORT_ERROR"
    TELEGRAM_SERVER_ERROR = "TELEGRAM_SERVER_ERROR"
    TELEGRAM_INVALID_RECEIPT = "TELEGRAM_INVALID_RECEIPT"
    TELEGRAM_CACHE_PERSISTENCE_ERROR = "TELEGRAM_CACHE_PERSISTENCE_ERROR"
    TELEGRAM_CACHE_METADATA_MISSING = "TELEGRAM_CACHE_METADATA_MISSING"


class SourceValidationConfidence(StrEnum):
    PROBED_WITH_NATIVE_PROVENANCE = "PROBED_WITH_NATIVE_PROVENANCE"


class QualityCandidateRejectionReason(StrEnum):
    PROVIDER_NOT_AVAILABLE = "PROVIDER_NOT_AVAILABLE"
    SOURCE_MEDIA_UNKNOWN = "SOURCE_MEDIA_UNKNOWN"
    LOSSY_TRANSCODE_FORBIDDEN = "LOSSY_TRANSCODE_FORBIDDEN"
    UPSCALE_FORBIDDEN = "UPSCALE_FORBIDDEN"
    TARGET_BITRATE_MISMATCH = "TARGET_BITRATE_MISMATCH"
    LOSSLESS_REQUIRED = "LOSSLESS_REQUIRED"


class MusicProviderName(StrEnum):
    APPLE_MUSIC = "apple_music"
    BANDCAMP = "bandcamp"
    DEEZER = "deezer"
    QOBUZ = "qobuz"
    SOUNDCLOUD = "soundcloud"
    SPOTIFY = "spotify"
    TIDAL = "tidal"
    YOUTUBE_MUSIC = "youtube_music"


class DeepLinkTargetType(StrEnum):
    TRACK = "TRACK"
    ALBUM = "ALBUM"


class DeepLinkStatus(StrEnum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"


class OperationalAuditEventType(StrEnum):
    ADMIN_PROMOTED = "ADMIN_PROMOTED"
    ADMIN_DEMOTED = "ADMIN_DEMOTED"
    WORKER_DESIRED_CHANGED = "WORKER_DESIRED_CHANGED"
    DEEP_LINK_REGISTERED = "DEEP_LINK_REGISTERED"
    DEEP_LINK_REVOKED = "DEEP_LINK_REVOKED"
    CRASH_RECOVERY_COMPLETED = "CRASH_RECOVERY_COMPLETED"
    MANUAL_RECOVERY_EXECUTED = "MANUAL_RECOVERY_EXECUTED"
    MANUAL_ARTIFACT_CLEANUP_EXECUTED = "MANUAL_ARTIFACT_CLEANUP_EXECUTED"
    SQLITE_BACKUP_CREATED = "SQLITE_BACKUP_CREATED"


class OperationalAuditActorKind(StrEnum):
    TELEGRAM_USER = "TELEGRAM_USER"
    INTERNAL_API = "INTERNAL_API"
    LOCAL_OPERATOR = "LOCAL_OPERATOR"
    SYSTEM = "SYSTEM"


class OperationalAuditTargetKind(StrEnum):
    USER = "USER"
    WORKER_POOL = "WORKER_POOL"
    DEEP_LINK = "DEEP_LINK"
    RECOVERY = "RECOVERY"
    ARTIFACT_CLEANUP = "ARTIFACT_CLEANUP"
    DATABASE_BACKUP = "DATABASE_BACKUP"


class NativeCodec(StrEnum):
    MP3 = "mp3"
    AAC = "aac"
    FLAC = "flac"
    VORBIS = "vorbis"
    OPUS = "opus"
    UNKNOWN = "unknown"
    OTHER = "other"


class NativeContainer(StrEnum):
    MP3 = "mp3"
    M4A = "m4a"
    FLAC = "flac"
    OGG = "ogg"
    WEBM = "webm"
    UNKNOWN = "unknown"
    OTHER = "other"


class ProviderRuntimeStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    UNAVAILABLE = "UNAVAILABLE"
    UNSUPPORTED = "UNSUPPORTED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    ERROR = "ERROR"


class ProviderHealthStatus(StrEnum):
    """Provider-level readiness, deliberately separate from TrackSource status."""

    READY = "READY"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    UNAVAILABLE = "UNAVAILABLE"
    ERROR = "ERROR"
    UNKNOWN = "UNKNOWN"


class ProviderHealthErrorCode(StrEnum):
    AUTH_NOT_CONFIGURED = "AUTH_NOT_CONFIGURED"
    SESSION_UNAVAILABLE = "SESSION_UNAVAILABLE"
    SESSION_UNVERIFIED = "SESSION_UNVERIFIED"
    SUBSCRIPTION_REQUIRED = "SUBSCRIPTION_REQUIRED"
    RUNTIME_UNAVAILABLE = "RUNTIME_UNAVAILABLE"
    PROVIDER_INITIALIZATION_FAILED = "PROVIDER_INITIALIZATION_FAILED"
    HEALTH_CHECK_TIMEOUT = "HEALTH_CHECK_TIMEOUT"
    UPSTREAM_ERROR = "UPSTREAM_ERROR"
    CREDENTIAL_EXPIRED = "CREDENTIAL_EXPIRED"
    CREDENTIAL_INVALID = "CREDENTIAL_INVALID"
    CREDENTIAL_REVOKED = "CREDENTIAL_REVOKED"


class ProviderResolutionStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    NO_AVAILABLE_PROVIDER = "NO_AVAILABLE_PROVIDER"


class TrackMatchDecision(StrEnum):
    MATCHED = "MATCHED"
    NEW_TRACK = "NEW_TRACK"
    AMBIGUOUS = "AMBIGUOUS"
    IDENTITY_CONFLICT = "IDENTITY_CONFLICT"


class TrackEvidenceCode(StrEnum):
    EXACT_SOURCE = "EXACT_SOURCE"
    ISRC_MATCH = "ISRC_MATCH"
    ISRC_CONFLICT = "ISRC_CONFLICT"
    TITLE_MATCH = "TITLE_MATCH"
    TITLE_CONFLICT = "TITLE_CONFLICT"
    ARTIST_MATCH = "ARTIST_MATCH"
    ARTIST_CONFLICT = "ARTIST_CONFLICT"
    DURATION_MATCH = "DURATION_MATCH"
    DURATION_LOOSE = "DURATION_LOOSE"
    DURATION_CONFLICT = "DURATION_CONFLICT"
    DURATION_UNKNOWN = "DURATION_UNKNOWN"
    VERSION_MATCH = "VERSION_MATCH"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    EXPLICIT_MATCH = "EXPLICIT_MATCH"
    EXPLICIT_CONFLICT = "EXPLICIT_CONFLICT"
    ALBUM_MATCH = "ALBUM_MATCH"


class ProviderDiscoveryStatus(StrEnum):
    INPUT = "INPUT"
    MATCHED = "MATCHED"
    NO_MATCH = "NO_MATCH"
    AMBIGUOUS = "AMBIGUOUS"
    UNAVAILABLE = "UNAVAILABLE"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    ERROR = "ERROR"
    IDENTITY_CONFLICT = "IDENTITY_CONFLICT"
